name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Quản lý trạng thái & Dependency Injection
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0

  # Kết nối mạng với Spring Boot
  dio: ^5.4.3+1

  # Phần cứng: Âm thanh, Giọng nói, Cảm biến, Định vị
  flutter_tts: ^4.0.2
  audioplayers: ^6.0.0
  geolocator: ^11.0.0
  sensors_plus: ^5.0.1

  # Lưu trữ ngoại tuyến (Offline-First)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Tiện ích UI
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true